spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
  # Postgre datasource
  datasource:
    username: sa
    url: jdbc:h2:file:/data/app;Mode=PostgreSQL
    hikari:
      connectionTimeout: '1000'
    driverClassName: org.h2.Driver
    password: password
  # Mongo datasource
  data:
    mongodb:
      host: localhost
      port: 27017
      database: embedded_db
frontend:
  url: http://localhost:4200
